### ISSUE TITLE
[Report] Create Diagram for Methodology

### ISSUE THREAD

**Issue by jantiegges** [jantiegges/comp550-final#12]
Create a diagram for our paper in LATEX, similar to the one in the Jagerman paper:
<img width="409" alt="Screenshot 2023-12-13 at 18 31 21" src="https://github.com/jantiegges/comp550-final/assets/52353665/ee0c3cdf-20ce-49ca-9b33-12d5564f8ef8">

**Comment by danielkappert** [comment]
Added below the methodology section
![image](https://github.com/jantiegges/comp550-final/assets/65031503/8bba84b2-ad41-4dda-8a7e-e2f39c48b31a)
